# GET http://localhost:4000/glossario/length

GET http://localhost:4000/glossario


# DELETE http://localhost:4000/delet-glossario/13 HTTP/1.1

//DELETE http://localhost:4000/delet-glossario/6405d949708be81590db8be2 HTTP/1.1
//usar essa rota : routes.delete("/delet-glossario/:_id", GlossarioController.delete)

//Update

# PUT http://localhost:4000/edit-glossario/46
# content-type: application/json

# {
#     "id": 15,
#     "palavra": "Loremipson2",
#     "descricao": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias atque fugiat itaque necessitatibus dolore voluptates nulla dolorum eligendi. Iste rem doloremque nostrum nesciunt a minus mollitia adipisci! Repudiandae, id perspiciatis.",
#     "vinculo": "cultura"
# }

//create (pra funcionar esse ou o put deve retirar primeiro
POST http://localhost:4000/cad-glossario
content-type: application/json

{
    "id": 2,
    "palavra": "lorem",
    "descricao": "Lorem dsdsdsdipsum dolor sit, amet consectetur adipisicing elit. Alias atque fugiat itaque necessitatibus dolore voluptates nulla dolorum eligendi. Iste rem doloremque nostrum nesciunt a minus mollitia adipisci! Repudiandae, id perspiciatis.",
    "vinculo": "cultura"
}
